

###
GET http://127.0.0.1:3000/testing
###

POST http://127.0.0.1:3000/registration
Content-Type: application/json

{
    "userEmail": "somethingUnique245@yahoo.com",
    "userPassword":"Appl3Sauc3_500"
}

###

POST http://127.0.0.1:3000/login
Content-Type: application/json

{
    "userEmail": "calhounbryce13@gmail.com",
    "userPassword": "Jarvis123"
}

###


POST http://127.0.0.1:3000/current-projects

connect.sid=s%3AbwW9whTpWMWf22RtH2yxh4DI-x2QxUk6.9xgy5JmpG0JYU4rF%2BUFbNtnHFr5sF3th4SoeDJw7Cb8


###

POST http://127.0.0.1:3000/add-planned-projects
Content-Type: application/json
Cookie: connect.sid=s%3A0p7WqMaa6whF_caSo6P8SwCMbm9V7xFU.CJsTafOVdEDJW1Uk%2BK5mGyFti0PUhC%2FxPAiwyCRi8M4

{
    "title":"to you, from me",
    "goal":"something something darkside"
}


###


POST http://127.0.0.1:3000/logout

connect.sid=s%3AbwW9whTpWMWf22RtH2yxh4DI-x2QxUk6.9xgy5JmpG0JYU4rF%2BUFbNtnHFr5sF3th4SoeDJw7Cb8


###

POST http://127.0.0.1:3000/add-current-projects