

###
GET http://127.0.0.1:3000/testing
###

POST http://127.0.0.1:3000/registration
Content-Type: application/json

{
    "userEmail": "somethingUnique345@yahoo.com",
    "userPassword":"Appl3Sauc3_500"
}

###

POST http://127.0.0.1:3000/login
Content-Type: application/json

{
    "userEmail": "somethingUnique345@yahoo.com",
    "userPassword": "Appl3Sauc3_500"
}

###


POST http://127.0.0.1:3000/logout

connect.sid=s%3A_2TPh6HHdbjRScurxFOJ85miuJiqwe0J.tAJmQdtdkDB0sKkw7aPjdBhEUmuN4Mb4cw9myTezpOI

