

###
GET http://127.0.0.1:3000/testing
###

POST http://127.0.0.1:3000/registration
Content-Type: application/json

{
    "userEmail": "somethingUnique245@yahoo.com",
    "userPassword":"Appl3Sauc3_500"
}

###

POST http://127.0.0.1:3000/login
Content-Type: application/json

{
    "userEmail": "calhounbryce13@gmail.com",
    "userPassword": "Jarvis123"
}

###


POST http://127.0.0.1:3000/logout

connect.sid=s%3AqDkY5S4wR9Vc-CPx9rcbOD-JW1fF4F6y.E4NDXGF%2B3x8qE%2BvQvCx7bnGdxCk2v4TVpJi7%2BpY3vL8